config/routes.rb
Rails.application.routes.draw do
  
  get 'devocionales' => 'main#all_days', :as => 'all_days'
  get 'devocional_de_hoy(/:id)' => 'main#today', :as => 'today'
  get 'descargar_devocional/:id' => 'main#download_devotional', :as => 'download_devotional'

  devise_for :users
  
  resources :devotionals, :except => [:show]

  root 'main#all_days'

end

app/controllers/main_controller.rb
class MainController < ApplicationController
  
  def all_days
    offset = 0
    total_per_page = 6
    @page = 1

    if params[:page]
      @page = params[:page].to_i
      offset = total_per_page * (@page - 1)
    end

  	@devotionals = Devotional.order("id DESC").limit(total_per_page).offset(offset)
    @total_pages = Devotional.count / total_per_page

    if @page > 0
      @previous_page_path = "?page=" + (@page - 1).to_s
    else
      if (@page + 1)*10 < Devotional.count
        @next_page_path = "?page=" + (@page + 1).to_s
      end
    end 

    if Devotional.count % total_per_page > 0
      @total_pages += 1
    end
  end

  def today
  	start_date = Date.new(2015, 5, 21)

  	if !params[:id].nil?
  		@devotional = Devotional.find(params[:id])
  	else
  		today = Date.today
  		day = (today - start_date).to_i - 1

  		@devotional = Devotional.find_by_day(day) rescue nil

  		if @devotional.nil?
  			@devotional = Devotional.where('day>?', day).order('id ASC').first rescue Devotional.last
  		end
  	end

    if @devotional.nil?
      @devotional = Devotional.last
    end
  end

  def download_devotional
    @devotional = Devotional.find(params[:id])
    respond_to do |format|
      format.pdf do
        render pdf: "devocional_dia_#{@devotional.day}"
      end
    end
  end

end

app/helpers/main_helper.rb
module MainHelper
end

app/views/main/_devotional.html.erb
<div class="row">
    <div class="col-md-7 center">
        <a href="<%= today_url(devotional) %>">
            <% if devotional.image.url.nil? %>
                <img class="img-responsive img_center" src="http://placehold.it/700x300" alt="">
            <% else %>
                <%= image_tag devotional.image.url, :class => 'img-responsive img_center' %>
            <% end %>
        </a>
    </div>
    <div class="col-md-5">
        <h3><%= devotional.title %></h3>
        <h4><%= "Día: " + devotional.day.to_s %></h4>
        <h5><%= devotional.passage %></h5>

        <% if !devotional.brief.nil? && devotional.brief.strip != "" %>
            <p><%= devotional.brief %></p>
        <% else %>
            <p><%= truncate devotional.story, :length => 430 %></p>
        <% end %>
        <a class="btn btn-primary" href="<%= today_url(devotional) %>">Ir al devocional <span class="glyphicon glyphicon-chevron-right"></span></a>
    </div>
</div>

<hr>

app/views/main/_footer.html.erb
<footer>
  <div class="content">
    Copyright &copy; HablandoConDios.com <%= Time.now.year %>
  </div>

  <div class="vn_image">
    <%= link_to image_tag("vnlogo.jpg"), 'https://www.facebook.com/ibvidanueva/?fref=ts', :target => '_BLANK' %>
  </div>
</footer>

app/views/main/_header.html.erb
<header>
  <div class="title1">
    Hablando con Dios
  </div>

  <div class="logo">
    <%= link_to image_tag("minf.jpg"), 'https://www.facebook.com/pages/Ministerios-Infantiles-Iglesia-Bautista-Vida-Nueva/149171741803159?fref=ts', :target => '_BLANK' %>
  </div>

  <div class="title2">
    Un proyecto de
  </div>
</header>

app/views/main/all_days.html.erb
<%= render :partial => 'header' %>

<div class="container">
    <%= render :partial => 'devotional', :collection => @devotionals %>

    <!-- Pagination -->
    <div class="row text-center">
        <div class="col-lg-12">
            <ul class="pagination">
              <%
                total_pages = @total_pages
                i = 1

                if total_pages > 5
                  total_pages = @page + 5 < @total_pages ? @page + 5 : @total_pages
                  i = @page > 5 ? @page - 4 : 1
                end
              %>
                <% for value in i..total_pages %>
                    <li class="<%= @page == value ? 'active' : '' %>">
                        <a href="?page=<%= value %>"><%= value %></a>
                    </li>
                <% end %>
            </ul>
        </div>
    </div>
    <!-- /.row -->

    <hr>
</div>

<%= render :partial => 'footer' %>

app/views/main/download_devotional.pdf.erb
<html>
<head>
	<meta charset="UTF-8">
	<title>Devocional</title>
</head>

<body>
	<div>
		<h1><%= @devotional.title %></h1>
	</div>

	<% if !@devotional.image.url.nil? %>
		<div>
			<table>
				<tr>
					<td style="vertical-align:top;">
						<img src="<%= 'http://hablandocondios.com' + @devotional.image.url %>" width="300" />
					</td>
					<td width="20">
						&nbsp;&nbsp;&nbsp;
					</td>
					<td style="vertical-align:top;">
						<div>
							<% if !@devotional.passage.nil? && @devotional.passage.strip != "" %>
								<h3><%= @devotional.passage %></h3>
							<% end %>

							<% if !@devotional.passage_text.nil? && @devotional.passage_text.strip != "" %>
								<p>
									<%= format_to_br(@devotional.passage_text) %>
								</p>
							<% end %>
						</div>
					</td>
				</tr>
			</table>
		</div>
	<% else %>
		<div>
			<% if !@devotional.passage.nil? && @devotional.passage.strip != "" %>
				<h3><%= @devotional.passage %></h3>
			<% end %>

			<% if !@devotional.passage_text.nil? && @devotional.passage_text.strip != "" %>
				<p>
					<%= format_to_br(@devotional.passage_text) %>
				</p>
			<% end %>
		</div>
	<% end %>

	<div>
		<h3>Historia</h3>
		<p>	
			<%= format_to_br(@devotional.story) %>
		</p>
	</div>

	<% if !@devotional.questions.nil? && @devotional.questions.strip != "" %>
		<div>
			<h3>Preguntas</h3>
			<p>	
				<%= format_to_br(@devotional.questions) %>
			</p>
		</div>
	<% end %>

	<div>
		<% if !@devotional.passage_mem.nil? && @devotional.passage_mem.strip != "" %>
			<h3>Pasaje a memorizar</h3>
			<p>	
				<%= @devotional.passage_mem %>
			</p>
			<br>
		<% end %>

		<% if !@devotional.quote.nil? && @devotional.quote.strip != "" %>
			<p>	
				<%= @devotional.quote %>
			</p>
		<% end %>
	</div>
</body>
</html>

app/views/main/today.html.erb
<%= render :partial => 'header' %>

<div class="container">
    <div class="row">
        <div class="col-lg-8">
            <h1 class="page-header"><%= @devotional.title %>
                <small>Día: <%= @devotional.day.to_s %></small>
            </h1>
        </div>

        <div class="col-lg-4 right">
            <h3 class="page-header">
                <a href="<%= all_days_url %>">Ver todos los devocionales</a>
            </h3>
        </div>
    </div>

    <div class="row">

        <div class="col-md-7 center">
            <% if @devotional.image.url.nil? %>
                <img class="img-responsive" src="http://placehold.it/700x300" alt="">
            <% else %>
                <%= image_tag @devotional.image.url, :class => 'img-responsive' %>
            <% end %>
            <br />

            <% if @devotional.file.url.nil? %>
                <%= link_to 'Descargar PDF', download_devotional_path(@devotional, :format => 'pdf'), :class => 'btn btn-success' %>
            <% else %>
                <%= link_to 'Descargar Documento', @devotional.file.url, :class => 'btn btn-success' %>
            <% end %>
        </div>

        <% if !@devotional.passage_text.nil? && @devotional.passage_text.strip != "" %>
            <div class="col-md-5">
                <h3><%= @devotional.passage %></h3>
                <p>
                    <i><%= format_to_br(@devotional.passage_text) %></i>
                </p>
            </div>
        <% end %>
    </div>

    <div class="row">
    	<div class="col-md-12">
            <h3>Historia</h3>
            <p>
            	<%= format_to_br(@devotional.story) %>
            </p>

            <% if !@devotional.questions.nil? && @devotional.questions.strip != "" %>
                <h3>Preguntas</h3>
                <p>
                	<%= format_to_br(@devotional.questions) %>
                </p>
            <% end %>

            <% if !@devotional.passage_mem.nil? && @devotional.passage_mem.strip != "" %>
                <h3>Pasaje a memorizar</h3>
                <p>
                	<blockquote><%= @devotional.passage_mem %></blockquote>
                </p>
            <% end %>
    	</div>
    </div>

    <% if !@devotional.quote.nil? && @devotional.quote.strip != "" %>
        <div class="row center">
            <div class="col-md-12">
                <i><%= @devotional.quote %></i>
            </div>
        </div>
    <% end %>

    <% if !@devotional.credits.nil? && @devotional.credits.strip != "" %>
        <hr />

        <div class="row center">
            <div class="col-md-12">
                <strong>Creditos: </strong><%= @devotional.credits %>
            </div>
        </div>
    <% end %>

<!--     <div class="row">
        <div class="col-lg-12">
            <h3 class="page-header">Otros devocionales</h3>
        </div>

        <div class="col-sm-3 col-xs-6">
            <a href="#">
                <img class="img-responsive portfolio-item" src="http://placehold.it/500x300" alt="">
            </a>
        </div>

        <div class="col-sm-3 col-xs-6">
            <a href="#">
                <img class="img-responsive portfolio-item" src="http://placehold.it/500x300" alt="">
            </a>
        </div>

        <div class="col-sm-3 col-xs-6">
            <a href="#">
                <img class="img-responsive portfolio-item" src="http://placehold.it/500x300" alt="">
            </a>
        </div>

        <div class="col-sm-3 col-xs-6">
            <a href="#">
                <img class="img-responsive portfolio-item" src="http://placehold.it/500x300" alt="">
            </a>
        </div>
    </div> -->
    <hr>
</div>

<%= render :partial => 'footer' %>