config/routes.rb
Rails.application.routes.draw do
  
  get 'devocionales' => 'main#all_days', :as => 'all_days'
  get 'devocional_de_hoy(/:id)' => 'main#today', :as => 'today'
  get 'descargar_devocional/:id' => 'main#download_devotional', :as => 'download_devotional'

  devise_for :users
  
  resources :devotionals, :except => [:show]

  root 'main#all_days'

end

app/models/devotional.rb
class Devotional < ActiveRecord::Base

  mount_uploader :image, DevotionalImageUploader
  mount_uploader :file, FileUploader
  
end

app/controllers/devotionals_controller.rb
class DevotionalsController < ApplicationController
  before_action :set_devotional, only: [:show, :edit, :update, :destroy]

  # GET /devotionals
  # GET /devotionals.json
  def index
    @devotionals = Devotional.all
  end

  # GET /devotionals/1
  # GET /devotionals/1.json
  def show
  end

  # GET /devotionals/new
  def new
    pdevotional = Devotional.last.day + 1 rescue 1
    @devotional = Devotional.new
    @devotional.day = pdevotional
  end

  # GET /devotionals/1/edit
  def edit
  end

  # POST /devotionals
  # POST /devotionals.json
  def create
    @devotional = Devotional.new(devotional_params)

    respond_to do |format|
      if @devotional.save
        format.html { redirect_to devotionals_url, notice: 'El devocional ha sido creado.' }
        format.json { render :show, status: :created, location: @devotional }
      else
        format.html { render :new }
        format.json { render json: @devotional.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /devotionals/1
  # PATCH/PUT /devotionals/1.json
  def update
    respond_to do |format|
      if @devotional.update(devotional_params)
        format.html { redirect_to devotionals_url, notice: 'El devocional ha sido actualizado.' }
        format.json { render :show, status: :ok, location: @devotional }
      else
        format.html { render :edit }
        format.json { render json: @devotional.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /devotionals/1
  # DELETE /devotionals/1.json
  def destroy
    @devotional.destroy
    respond_to do |format|
      format.html { redirect_to devotionals_url, notice: 'El devocional ha sido eliminado' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_devotional
      @devotional = Devotional.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def devotional_params
      params.require(:devotional).permit(:title, :day, :passage, :passage_text, :story, :questions, :passage_mem, :quote, :image, :file, :credits, :brief)
    end
end

app/helpers/devotionals_helper.rb
module DevotionalsHelper
end

app/views/devotionals/_form.html.erb
<%= form_for @devotional, :html => {:multipart => true} do |f| %>
  <% if @devotional.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@devotional.errors.count, "error") %> prohibited this devotional from being saved:</h2>

      <ul>
      <% @devotional.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    *<%= f.label :title, t('title') %><br>
    <%= f.text_field :title, :class => 'form-control', :required => true %>
  </div>
  <div class="field form-group">
    *<%= f.label :day, t('day') %><br>
    <%= f.number_field :day, :class => 'form-control', :required => true %>
  </div>
  <div class="field form-group">
    <%= f.label :brief, t('brief') %><br>
    <%= f.text_area :brief, :class => 'form-control', :rows => 3 %>
  </div>
  <div class="field form-group">
    <%= f.label :passage, t('passage') %><br>
    <%= f.text_field :passage, :class => 'form-control', :required => false %>
  </div>
  <div class="field form-group">
    <%= f.label :passage_text, t('passage_text') %><br>
    <%= f.text_area :passage_text, :class => 'form-control', :required => false, :rows => 6 %>
  </div>
  <div class="field form-group">
    <%= f.label :story, t('story') %><br>
    <%= f.text_area :story, :class => 'form-control', :required => false, :rows => 12 %>
  </div>
  <div class="field form-group">
    <%= f.label :questions, t('questions') %><br>
    <%= f.text_area :questions, :class => 'form-control', :required => false, :rows => 4 %>
  </div>
  <div class="field form-group">
    <%= f.label :passage_mem, t('passage_mem') %><br>
    <%= f.text_field :passage_mem, :class => 'form-control', :required => false %>
  </div>
  <div class="field form-group">
    <%= f.label :quote, t('quote') %><br>
    <%= f.text_field :quote, :class => 'form-control', :required => false %>
  </div>
  <div class="field form-group">
    <%= f.label :image, t('image_name') %><br>
    <%= f.file_field :image, :class => 'form-control' %>
  </div>
  <div class="field form-group">
    <%= f.label :file, t('file_name') %><br>
    <%= f.file_field :file, :class => 'form-control' %>
  </div>
  <div class="field form-group">
    <%= f.label :credits, t('credits') %><br>
    <%= f.text_field :credits, :class => 'form-control', :required => false %>
  </div>
  <div class="actions">
    <%= link_to t('back'), devotionals_path, :class => "btn btn-default" %>
    <%= f.submit t('save'), :class => "btn btn-success" %>
  </div>
<% end %>

app/views/devotionals/edit.html.erb
<h1><%= @devotional.title %></h1>

<%= render 'form' %>

app/views/devotionals/index.html.erb
<h1><%= t('devotionals') %></h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th><%= t('title') %></th>
      <th><%= t('day') %></th>
      <th><%= t('passage') %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @devotionals.each do |devotional| %>
      <tr>
        <td><%= devotional.title %></td>
        <td><%= devotional.day %></td>
        <td><%= devotional.passage %></td>
        <td><%= link_to t('edit'), edit_devotional_path(devotional) %></td>
        <td><%= link_to t('remove'), devotional, method: :delete, data: { confirm: t('are_you_sure_to_remove_the_dev') } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('new_devotional'), new_devotional_path, :class => "btn btn-default" %>

app/views/devotionals/new.html.erb
<h1><%= t('new_devotional') %></h1>

<%= render 'form' %>

app/views/devotionals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @devotional.title %>
</p>

<p>
  <strong>Day:</strong>
  <%= @devotional.day %>
</p>

<p>
  <strong>Passage:</strong>
  <%= @devotional.passage %>
</p>

<p>
  <strong>Passage text:</strong>
  <%= @devotional.passage_text %>
</p>

<p>
  <strong>Story:</strong>
  <%= @devotional.story %>
</p>

<p>
  <strong>Questions:</strong>
  <%= @devotional.questions %>
</p>

<p>
  <strong>Passage mem:</strong>
  <%= @devotional.passage_mem %>
</p>

<p>
  <strong>Quote:</strong>
  <%= @devotional.quote %>
</p>

<%= link_to 'Edit', edit_devotional_path(@devotional) %> |
<%= link_to 'Back', devotionals_path %>